# Generated by Django 5.1.15 on 2026-08-15 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('disaster_type', models.CharField(choices=[('flood', 'Flood'), ('cyclone', 'Cyclone'), ('earthquake', 'Earthquake'), ('fire', 'Fire'), ('landslide', 'Landslide'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved')], default='active', max_length=12)),
                ('location', models.CharField(max_length=250)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('affected_population', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disasters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(max_length=250)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('evidence_ref', models.CharField(blank=True, max_length=60)),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='core.disaster')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='analysis/')),
                ('overall_confidence', models.FloatField(default=0.0)),
                ('summary', models.TextField(blank=True)),
                ('model_used', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='core.disaster')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_type', models.CharField(choices=[('damaged_building', 'Damaged Building'), ('blocked_road', 'Blocked Road'), ('service_disruption', 'Service Disruption'), ('other', 'Other')], max_length=30)),
                ('label', models.CharField(max_length=200)),
                ('location_hint', models.CharField(blank=True, max_length=250)),
                ('confidence', models.FloatField(default=0.0)),
                ('evidence', models.TextField(blank=True)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('confirmed', 'Confirmed'), ('corrected', 'Corrected'), ('rejected', 'Rejected')], default='unverified', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.disaster')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.imageanalysis')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriorityZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('structural_risk', models.FloatField(default=0.0)),
                ('population_exposure', models.FloatField(default=0.0)),
                ('vulnerability', models.FloatField(default=0.0)),
                ('accessibility', models.FloatField(default=0.0)),
                ('infrastructure_risk', models.FloatField(default=0.0)),
                ('evidence_confidence', models.FloatField(default=0.0)),
                ('priority_score', models.FloatField(default=0.0)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('confirmed', 'Confirmed'), ('corrected', 'Corrected'), ('rejected', 'Rejected')], default='unverified', max_length=12)),
                ('evidence_refs', models.JSONField(blank=True, default=list)),
                ('factors', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_zones', to='core.disaster')),
            ],
            options={
                'ordering': ['-priority_score'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('administrator', 'Administrator'), ('incident_commander', 'Incident Commander'), ('field_responder', 'Field Responder'), ('analyst', 'Analyst'), ('verifier', 'Verifier')], default='analyst', max_length=32)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('organisation', models.CharField(blank=True, max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('incident', 'Incident'), ('damage', 'Damage'), ('casualty', 'Casualty'), ('infrastructure', 'Infrastructure'), ('rescue_request', 'Rescue Request'), ('resource_requirement', 'Resource Requirement'), ('other', 'Other')], default='incident', max_length=25)),
                ('description', models.TextField()),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('confirmed', 'Confirmed'), ('corrected', 'Corrected'), ('rejected', 'Rejected')], default='unverified', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.disaster')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responder_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('administrator', 'Administrator'), ('incident_commander', 'Incident Commander'), ('field_responder', 'Field Responder'), ('analyst', 'Analyst'), ('verifier', 'Verifier')], default='field_responder', max_length=32)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('task', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='assigned', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.disaster')),
                ('responder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.priorityzone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=200)),
                ('start_lat', models.FloatField()),
                ('start_lng', models.FloatField()),
                ('dest_location', models.CharField(max_length=200)),
                ('dest_lat', models.FloatField()),
                ('dest_lng', models.FloatField()),
                ('distance_km', models.FloatField(default=0.0)),
                ('est_minutes', models.FloatField(default=0.0)),
                ('blocked_roads', models.JSONField(blank=True, default=list)),
                ('route_status', models.CharField(choices=[('passable', 'Passable according to available data'), ('obstruction', 'Potential obstruction reported'), ('blocked', 'Blocked according to available data'), ('unavailable', 'Route information unavailable')], default='unavailable', max_length=15)),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='core.disaster')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('confirm', 'Confirm'), ('correct', 'Correct'), ('reject', 'Reject')], max_length=10)),
                ('correct_classification', models.CharField(blank=True, choices=[('damaged_building', 'Damaged Building'), ('blocked_road', 'Blocked Road'), ('service_disruption', 'Service Disruption'), ('other', 'Other')], max_length=30)),
                ('reason', models.CharField(blank=True, max_length=250)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='core.finding')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
